name: Remove Carriage Return (Ctrl + M)

on:
  push:
    branches:
      - '**'  # Trigger on any push to any branch
  pull_request:
    branches:
      - '**'  # Trigger on any pull request targeting any branch

jobs:
  remove-crlf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove carriage return characters
      run: |
        # Find and remove all carriage return characters from all files
        find . -type f -exec sed -i 's/\r//g' {} \;

    - name: Commit changes with the correct user info
      run: |
        # Set the author name and email based on who triggered the action (push/pull request)
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        
        # Add and commit changes
        git add .
        git commit -m "Remove carriage return characters"
        git push
      continue-on-error: true  # Avoid failing if there are no changes
